# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Danil/Downloads/DAS_labs/projects/lab8/lab8.srcs/sources_1/ip/Refresh_RAM/Refresh_RAM.xci
# IP: The module: 'Refresh_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Danil/Downloads/DAS_labs/projects/lab8/lab8.gen/sources_1/ip/Refresh_RAM/Refresh_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Refresh_RAM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Danil/Downloads/DAS_labs/projects/lab8/lab8.srcs/sources_1/ip/Refresh_RAM/Refresh_RAM.xci
# IP: The module: 'Refresh_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Danil/Downloads/DAS_labs/projects/lab8/lab8.gen/sources_1/ip/Refresh_RAM/Refresh_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Refresh_RAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
